# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-ca
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-ca
  contentDir: content/zh
  title: English website...
  params:
    description: Site description in english...
  menu:
    main:
      - name: en
        url: '#about'
        weight: 1
