# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
fr:
  languageCode: fr-ca
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/fr

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-ca
  contentDir: content/en
  title: Ernzerhof Group
  params:
    description: Ernzerhof Group
  menu:
    main:
      - name: Research
        url: research
        weight: 20
      - name: Team
        url: people
        weight: 30
      - name: Publications
        url: publication
        weight: 50