# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-ca
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content

# Uncomment the lines below to configure your website in a second language.
#en:
#  languageCode: fr-ca
#  contentDir: content/fr
#  title: Groupe Ernzerhof
#  params:
#    description: Groupe Ernzerhof
#  menu:
#  
#     main:
#       - name: Recherche
#         url: research
#         weight: 20
#       - name: Équipe
#         url: people
#         weight: 30
#       - name: Publications
#         url: publication
#         weight: 50